# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: MOOBAY
email: moobay@foxmail.com
description: > # this means to ignore newlines until "baseurl:"
  猴哥 师傅被妖怪抓走了
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  moobay

# Build settings
markdown: kramdown
# kramdown:
#   input: GFM
#   # https://github.com/jekyll/jekyll/pull/4090
#   syntax_highlighter: rouge
#
#   # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
#   # span, block element options fall back to global
#   syntax_highlighter_opts:
#     # Rouge Options › https://github.com/jneen/rouge#full-options
#     css_class: 'highlight'
#     #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
#     span:
#       line_numbers: false
#     block:
#       line_numbers: true
#       start_line: 1
#
# highlight:
#   linenos: true

# theme: jekyll-theme-leap-day
theme: jekyll-theme-cayman

gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
  
paginate: 5          # Posts per page on the blog index
paginate_path: "posts/:num"  # Directory base for pagination URLs eg. /posts/2/
recent_posts: 10       # Posts in the sidebar Recent Posts section
excerpt_link: "正文&raquo;"  # "Continue reading" link text at the bottom of excerpted articles
excerpt_separator: <!--more-->

titlecase: false       # Converts page and post titles to titlecase
